baseurl = "http://git.bookislife.com/"
title = "Pixel Space"
languageCode = "zh"
disqusShortname = "gitpixelspace"
copyright = "Copyright (c) 2015, Sidney Xu; all rights reserved."
MetaDataFormat = "yaml"
paginate = 10

[permalinks]
    post = "/:section/:year/:slug/"
    project = "/:section/:year/:slug/"

[author]
    name = "Sidney Xu"

[indexes]
    tag = "tags"
    topic = "topics"

[params]
    avatar = "http://7xlqqp.com1.z0.glb.clouddn.com/6219353%20(1).png"
    description = "Book is life"
    since = "2015"
    #twitter = ""
    #facebook = ""
    #linkedin = ""
    github = "SidneyXu"
    #gplus = ""
    slideshare = "siriuseddy"
    googleAnalytics = "UA-66541663-1"
    baiduAnalytics = "1dcca96f408870b7c0b33bb3ad210577"
    dateformater = "2006-01-02"
    #swiftType = ""
    flagcounter = "1fWDHae"

