baseurl = "http://git.bookislife.com/"
title = "Pixel Space"
languageCode = "zh"
disqusShortname = "gitpixelspace"
copyright = "Copyright (c) 2015, Sidney Xu; all rights reserved."
MetaDataFormat = "yaml"
paginate = 10
 
[author]
    name = "Sidney Xu"

[indexes]
    tag = "tags"
    topic = "topics"

[params]
    description = "Book is life"
    twitter = "abc"
    facebook = "df"
    linkedin = ""
    github = "SidneyXu"
    gplus = ""
    slideshare = "siriuseddy"
    googleAnalytics = "UA-66541663-1"
    dateformater = "2006/01/01"

