baseurl = "http://git.bookislife.com/"
title = "Pixel Space"
languageCode = "zh-cn"
disqusShortname = "gitpixelspace"
copyright = "Copyright (c) 2015, Sidney Xu; all rights reserved."
MetaDataFormat = "yaml"
paginate = 10
 
[author]
    name = "Sidney Xu"
    #DisplayName = "abc"

[indexes]
    tag = "tags"
    topic = "topics"

[params]
    description = "Book is life"
    twitter = "abc"
    facebook = "df"
